# Generated by Django 5.2.1 on 2025-05-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medico_especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_especialidade_id', models.IntegerField(verbose_name=enumerate)),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_id', models.IntegerField(verbose_name=enumerate)),
                ('nome', models.CharField(max_length=50)),
                ('crm', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='')),
                ('cpf', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=300)),
                ('especialidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.medico_especialidade')),
            ],
        ),
        migrations.AddField(
            model_name='medico_especialidade',
            name='medico_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.medicos'),
        ),
        migrations.CreateModel(
            name='consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_id', models.IntegerField()),
                ('data_hora', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('created_at', models.TimeField()),
                ('consulta_id', models.IntegerField(verbose_name=enumerate)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='prontuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario_id', models.IntegerField(verbose_name=enumerate)),
                ('diagnostico', models.TextField(max_length=200)),
                ('prescicao', models.TextField(max_length=200)),
                ('observacoes', models.TextField(max_length=200)),
                ('created_at', models.TimeField()),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consultas')),
            ],
        ),
    ]
